# Generated by Django 4.2.11 on 2024-04-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('shipper', 'Shipper')], default='user', max_length=20),
        ),
    ]
