# Generated by Django 4.2.11 on 2024-04-03 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_shipper_approved',
            new_name='is_approved',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('shipper', 'Shipper'), ('user', 'User')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cccd', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
