# Generated by Django 4.2.11 on 2024-05-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auction_order_review_remove_comment_lesson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipper',
            new_name='shipper_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
