# Generated by Django 4.2.11 on 2024-05-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_order_auction_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='shipper_id',
            new_name='shipper',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipper_id',
            new_name='shipper',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='shipper_id',
            new_name='shipper',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shipper',
            old_name='user_id',
            new_name='user',
        ),
    ]
