# Generated by Django 4.2.11 on 2024-05-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_user_id_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipper',
            new_name='shipper_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
