# Generated by Django 4.2.11 on 2024-05-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_shipper_order_shipper_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipper_id',
            new_name='shipper',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
    ]
